sonar.projectKey=receitasapi
sonar.projectName=ReceitasApi
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=api/src/main/java,receitasapi-ui/src
sonar.tests=api/src/test/java,receitasapi-ui/src,receitasapi-ui/tests,receitasapi-ui/cypress/e2e

sonar.exclusions=**/target/**,**/dist/**,**/coverage/**,**/node_modules/**,**/*.spec.ts,**/*.spec.js,**/*.cy.ts,**/*.cy.js,**/main.ts,**/main.server.ts,**/server.ts
sonar.test.inclusions=**/*.spec.ts,**/*.spec.js,**/*.cy.ts,**/*.cy.js

sonar.java.binaries=api/target/classes
sonar.coverage.jacoco.xmlReportPaths=api/target/site/jacoco/jacoco.xml

# Cobertura do frontend (gerada por npm run test:coverage)
sonar.javascript.lcov.reportPaths=receitasapi-ui/coverage/lcov.info
sonar.typescript.lcov.reportPaths=receitasapi-ui/coverage/lcov.info