# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/gourmethub
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (bom para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta da API
server.port=8080